[[redirects]]
  from = "/api/*"
  to = "https://radwan2632.pythonanywhere.com/api/:splat"
  status = 200
[build]
  command = "pnpm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "vite"